name: test actions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: deploy
        run: cd /home/ubuntu/projects/githubActoins
      - name: pullcode 
        run: git pull origin main
        
