name: test actions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: deploy
        run: |
          pwd
          cd /home/ubuntu/projects/githubActions
          git pull origin main
