name: test actions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: deploy
        run: echo "Hello, world!"
             git pull origin main
        
